### ISSUE TITLE
refactor code 

### ISSUE THREAD

**Issue by catalinconstant** [ka7eh/rust-mbtileserver#2]
looking at the code in config.rs I think that 
<code>
let disable_preview = if matches.occurrences_of("disable_preview") != 0 {
        true
    } else {
        false
    };
</code>
is equivalent to 
<code>
let disable_preview = matches.occurrences_of("disable_preview") != 0;
</code>

**Comment by ka7eh** [comment]
You're completely right! :)
I've changed it here: https://github.com/ka7eh/rust-mbtileserver/commit/3a8b030efd861c69c61644ad3ee719f322af92e9#diff-6d8a5e2104954a026de2bfe2b936aea4R93
