### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by catalinconstant** [ka7eh/rust-mbtileserver#3]
Looking at the code I have observed the following:
1. you use .split(",")  &str better and faster will be .spli(',') char;
2. you addnotate for example get_tile_details<'a>  lifetime, never used, better  just  get_tile_details

**Comment by ka7eh** [comment]
Thanks for the hints. I updated those in https://github.com/ka7eh/rust-mbtileserver/commit/1b1c81b6a4f352fa722182f89d889fc05194c68e.
